#!/usr/bin/python

"""
Converts data generated by etree.py to a series of MySQL INSERT commands.

Usage example:

cat plwiki*/plwik*.xml.bz2-govonly2 | \
    grep -v '^Interesting' | \
    python ./frontend/tosql.py rdns.txt

rDNS file can be generated like this:

cat plwiki*/plwik*.xml.bz2-govonly2 | \
    grep -v '^Intereresting' | \
    cut -d"'" -f2 | \
    sort | \
    uniq | \
    parallel -I'{}' 'echo -n "{}	"; dig "+short" -x "{}"' > rdns.txt

(might need manual editing)

"""

import sys
import MySQLdb
sql = 'INSERT INTO plgov_entries (title, ip, rdns, timestamp, url) \
VALUES ("%s", "%s", "%s", "%s", "%s");'
rdns = {}
with open(sys.argv[1]) as rdns_file:
    for line in rdns_file:
        split = line.split()
        if len(split) != 2:
            continue
        rdns[split[0]] = split[1].rstrip('.')
for line in sys.stdin:
    ip, title, timestamp, url = eval(line)
    id_ = url.split('=')[-1]
    print(sql % tuple(MySQLdb.escape_string(s.encode('utf8'))
        for s in [title, ip, rdns.get(ip, ''), timestamp, url]))
